name: Java 17 APK Build and Release 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build APK
      run: |
        ./gradlew assembleRelease
        
    - name: Debug APK file path
      run: ls -R app/build/outputs/apk
      
    - name: Upload APK as release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.repository.releases_url }}
        asset_path: app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
        token: ${{ secrets.GH_TOKEN }}
