name: Java 17 APK Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build APK
      run: |
        ./gradlew assembleRelease
        
    - name: Debug APK file path
      run: ls -R app/build/outputs/apk
      
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
