name: Java 17 APK Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build APK
      run: |
        ./gradlew assembleRelease
        
    - name: Debug APK file path
      run: ls -R app/build/outputs/apk
      
    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Upload APK to VM
      run: |
        sshpass -p "Fazi11223344" scp app/build/outputs/apk/release/app-release-unsigned.apk faizanali@68.154.41.125:/var/www/html
